package socialEvents::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'socialEvents::Schema',
    
    connect_info => {
        dsn => 'dbi:Oracle:sid=xe;host=192.168.1.138;port=1521',
        user => 'fabiim',
        password => 'pass',
        AutoCommit => q{1},
	on_connect_call => 'datetime_setup',
    }
);

=head1 NAME

socialEvents::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<socialEvents>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<socialEvents::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.48

=head1 AUTHOR

fabiim

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
